In [2]:
import numpy as np
from pythtb import *
from itertools import product

In [4]:
x = 15

In [5]:
y = 5

In [13]:
x+y

30

Notice difference in indicing. The first gets the first element of all the rows, and the second gets the elements of the first row

In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
A[:, 0]

array([1, 3])

In [4]:
A[:][0]


array([1, 2])

In [17]:
nks = 20, 20

In [20]:
k_vals = [range(nk) for nk in nks]
k_idx_arr = np.array(list(product(*k_vals)))

In [21]:
for k in k_idx_arr:
    print (k)

[0 0]
[0 1]
[0 2]
[0 3]
[0 4]
[0 5]
[0 6]
[0 7]
[0 8]
[0 9]
[ 0 10]
[ 0 11]
[ 0 12]
[ 0 13]
[ 0 14]
[ 0 15]
[ 0 16]
[ 0 17]
[ 0 18]
[ 0 19]
[1 0]
[1 1]
[1 2]
[1 3]
[1 4]
[1 5]
[1 6]
[1 7]
[1 8]
[1 9]
[ 1 10]
[ 1 11]
[ 1 12]
[ 1 13]
[ 1 14]
[ 1 15]
[ 1 16]
[ 1 17]
[ 1 18]
[ 1 19]
[2 0]
[2 1]
[2 2]
[2 3]
[2 4]
[2 5]
[2 6]
[2 7]
[2 8]
[2 9]
[ 2 10]
[ 2 11]
[ 2 12]
[ 2 13]
[ 2 14]
[ 2 15]
[ 2 16]
[ 2 17]
[ 2 18]
[ 2 19]
[3 0]
[3 1]
[3 2]
[3 3]
[3 4]
[3 5]
[3 6]
[3 7]
[3 8]
[3 9]
[ 3 10]
[ 3 11]
[ 3 12]
[ 3 13]
[ 3 14]
[ 3 15]
[ 3 16]
[ 3 17]
[ 3 18]
[ 3 19]
[4 0]
[4 1]
[4 2]
[4 3]
[4 4]
[4 5]
[4 6]
[4 7]
[4 8]
[4 9]
[ 4 10]
[ 4 11]
[ 4 12]
[ 4 13]
[ 4 14]
[ 4 15]
[ 4 16]
[ 4 17]
[ 4 18]
[ 4 19]
[5 0]
[5 1]
[5 2]
[5 3]
[5 4]
[5 5]
[5 6]
[5 7]
[5 8]
[5 9]
[ 5 10]
[ 5 11]
[ 5 12]
[ 5 13]
[ 5 14]
[ 5 15]
[ 5 16]
[ 5 17]
[ 5 18]
[ 5 19]
[6 0]
[6 1]
[6 2]
[6 3]
[6 4]
[6 5]
[6 6]
[6 7]
[6 8]
[6 9]
[ 6 10]
[ 6 11]
[ 6 12]
[ 6 13]
[ 6 14]
[ 6 15]
[ 6 16]
[ 6 17]
[ 6 18]
[ 6 19]
[7 0]
[7 1]
[7 2]
[7

$ x+y=z$
$$\psi_{n,k}$$

Matrix Exponential

In [1]:
import numpy as np

In [18]:
def add(x, y):
    return x+y

add(2, 3)

5

In [20]:
def add(x,y):
    return x-y

add(2,3)

-1

In [21]:
add(5, 6)

-1

In [17]:
def exp(M):
    shape = M.shape
    nk = len(shape[:-2])
    trans_ax = [i for i in range(nk)] + [nk+1, nk]

    _, eigvecs = np.linalg.eig(M)
    U = np.transpose(eigvecs, axes=trans_ax) # [orb, num_evecs]
    diagM = np.einsum('...ij,...jk->...ik', U, np.einsum('...ij,...jk->...ik', M, np.transpose(U, axes=trans_ax).conj()) )
    # print(diagM[0].round(5))
    exp_diagM = np.exp(np.diagonal(diagM, axis1=-1, axis2=-2))
    expM = np.einsum('...ij, ...jk -> ...ik', np.transpose(U.conj(), axes=trans_ax), np.multiply(U, exp_diagM[..., :, np.newaxis]))
    return(expM)

def exp2(M):
    shape = M.shape
    nk = len(shape[:-2])
    trans_ax = [i for i in range(nk)] + [nk + 1, nk]

    eigvals, eigvecs = np.linalg.eig(M)
    U = eigvecs
    U_inv = np.linalg.inv(U)

    # Diagonal matrix of the exponentials of the eigenvalues
    exp_diagM = np.exp(eigvals)

    # Construct the matrix exponential
    # expM = np.einsum('...ij,...jk,...kl->...il', U, np.diagonal(exp_diagM, axis1=-1, axis2=-2), U_inv)
    expM = np.einsum('...ij,...jk->...ik', U, np.multiply(U_inv, exp_diagM[..., :, np.newaxis]))


    return expM

In [18]:
M = np.array([[np.random.random((3,3)) + np.random.random((3,3))*1j for i in range(2)]for j in range(2)])

M = (M + np.transpose(M.conj(), axes=(0, 1, 3, 2)))/2j
M

array([[[[ 0.        -0.16747663j,  0.21047385-0.81393551j,
           0.11858771-0.51666164j],
         [-0.21047385-0.81393551j,  0.        -0.26722116j,
          -0.19095513-0.15502305j],
         [-0.11858771-0.51666164j,  0.19095513-0.15502305j,
           0.        -0.3202433j ]],

        [[ 0.        -0.06907967j,  0.30918508-0.52200498j,
           0.13709591-0.6969659j ],
         [-0.30918508-0.52200498j,  0.        -0.26412257j,
           0.10047785-0.40668423j],
         [-0.13709591-0.6969659j , -0.10047785-0.40668423j,
           0.        -0.10869886j]]],


       [[[ 0.        -0.39534781j, -0.02450103-0.75723311j,
          -0.13128026-0.07757807j],
         [ 0.02450103-0.75723311j,  0.        -0.9599789j ,
          -0.04024925-0.64065041j],
         [ 0.13128026-0.07757807j,  0.04024925-0.64065041j,
           0.        -0.30552566j]],

        [[ 0.        -0.41022929j,  0.08774026-0.64637719j,
          -0.09885851-0.66106521j],
         [-0.08774026-0.64637719

In [14]:
# M = np.random.random((3,3)) + np.random.random((3,3))*1j 
# M = (M + np.transpose(M.conj(), axes=(1, 0)))/2j
# M

In [19]:
exp(M).round(5)

array([[[[ 0.68029-0.10403j, -0.28731-0.50306j, -0.23452-0.36846j],
         [-0.0067 -0.64191j,  0.73222-0.1914j , -0.03665-0.11744j],
         [-0.04881-0.33453j, -0.30104-0.0313j ,  0.85218-0.26057j]],

        [[ 0.76883-0.09607j, -0.32027-0.32566j, -0.26198-0.34988j],
         [ 0.01227-0.42979j,  0.80182-0.10434j, -0.1724 -0.36278j],
         [-0.01598-0.46319j, -0.14603-0.34095j,  0.80266-0.05793j]]],


       [[[ 0.71348-0.2395j , -0.4052 -0.50771j, -0.10725-0.01182j],
         [-0.40279-0.42353j,  0.28482-0.51524j, -0.32031-0.45738j],
         [-0.28894+0.09215j, -0.33243-0.34778j,  0.7968 -0.20412j]],

        [[ 0.62979-0.29329j, -0.28674-0.37863j, -0.37531-0.38847j],
         [-0.25997-0.302j  ,  0.77853-0.20643j, -0.39982-0.18064j],
         [-0.43135-0.41532j, -0.21303-0.2834j ,  0.53974-0.47375j]]]])

In [20]:
exp2(M).round(5)

array([[[[ 0.5483 -5.3820e-02j, -0.00826-7.4588e-01j,
          -0.06563-3.6845e-01j],
         [-0.32514-5.6905e-01j,  0.62876-1.6015e-01j,
          -0.386  -2.1860e-02j],
         [-0.28548-4.3061e-01j, -0.08382-1.2483e-01j,
           0.80475-2.5069e-01j]],

        [[ 0.60622+1.7260e-02j,  0.05322-4.4362e-01j,
          -0.02053-6.5738e-01j],
         [-0.45734-3.7660e-01j,  0.73   -1.6458e-01j,
          -0.15204-2.5673e-01j],
         [-0.2257 -4.7986e-01j, -0.33555-3.5748e-01j,
           0.69109-2.8250e-02j]]],


       [[[ 0.7009 -2.2638e-01j, -0.41029-4.3198e-01j,
          -0.30247+1.0516e-01j],
         [-0.41701-5.2018e-01j,  0.25758-4.9897e-01j,
          -0.33739-3.5549e-01j],
         [-0.11405-4.0000e-05j, -0.32988-4.7002e-01j,
           0.78745-1.9280e-01j]],

        [[ 0.57493-1.9341e-01j, -0.15063-4.3217e-01j,
          -0.49001-4.2717e-01j],
         [-0.36496-5.1161e-01j,  0.72098-2.1558e-01j,
          -0.12557-1.5165e-01j],
         [-0.28252-3.9659e-01j, -0.

In [21]:
from scipy.linalg import expm

expm(M).round(5)

array([[[[ 0.5483 -5.3820e-02j, -0.00826-7.4588e-01j,
          -0.06563-3.6845e-01j],
         [-0.32514-5.6905e-01j,  0.62876-1.6015e-01j,
          -0.386  -2.1860e-02j],
         [-0.28548-4.3061e-01j, -0.08382-1.2483e-01j,
           0.80475-2.5069e-01j]],

        [[ 0.60622+1.7260e-02j,  0.05322-4.4362e-01j,
          -0.02053-6.5738e-01j],
         [-0.45734-3.7660e-01j,  0.73   -1.6458e-01j,
          -0.15204-2.5673e-01j],
         [-0.2257 -4.7986e-01j, -0.33555-3.5748e-01j,
           0.69109-2.8250e-02j]]],


       [[[ 0.7009 -2.2638e-01j, -0.41029-4.3198e-01j,
          -0.30247+1.0516e-01j],
         [-0.41701-5.2018e-01j,  0.25758-4.9897e-01j,
          -0.33739-3.5549e-01j],
         [-0.11405-4.0000e-05j, -0.32988-4.7002e-01j,
           0.78745-1.9280e-01j]],

        [[ 0.57493-1.9341e-01j, -0.15063-4.3217e-01j,
          -0.49001-4.2717e-01j],
         [-0.36496-5.1161e-01j,  0.72098-2.1558e-01j,
          -0.12557-1.5165e-01j],
         [-0.28252-3.9659e-01j, -0.

In [155]:
%timeit exp2(M)

25.5 μs ± 561 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [156]:
%timeit expm(M)

247 μs ± 9.63 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [157]:
print(np.allclose(expm(M), exp2(M)))

True


In [30]:
np.random.normal(scale=0.01, size=(2,2))

array([[-0.01136108, -0.00660003],
       [-0.01977864, -0.00127006]])