In [1]:
import numpy as np
from pythtb import *
from itertools import product

Notice difference in indicing. The first gets the first element of all the rows, and the second gets the elements of the first row

In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
A[:, 0]


array([1, 3])

In [4]:
A[:][0]


array([1, 2])

In [17]:
nks = 20, 20

In [20]:
k_vals = [range(nk) for nk in nks]
k_idx_arr = np.array(list(product(*k_vals)))

In [21]:
for k in k_idx_arr:
    print (k)

[0 0]
[0 1]
[0 2]
[0 3]
[0 4]
[0 5]
[0 6]
[0 7]
[0 8]
[0 9]
[ 0 10]
[ 0 11]
[ 0 12]
[ 0 13]
[ 0 14]
[ 0 15]
[ 0 16]
[ 0 17]
[ 0 18]
[ 0 19]
[1 0]
[1 1]
[1 2]
[1 3]
[1 4]
[1 5]
[1 6]
[1 7]
[1 8]
[1 9]
[ 1 10]
[ 1 11]
[ 1 12]
[ 1 13]
[ 1 14]
[ 1 15]
[ 1 16]
[ 1 17]
[ 1 18]
[ 1 19]
[2 0]
[2 1]
[2 2]
[2 3]
[2 4]
[2 5]
[2 6]
[2 7]
[2 8]
[2 9]
[ 2 10]
[ 2 11]
[ 2 12]
[ 2 13]
[ 2 14]
[ 2 15]
[ 2 16]
[ 2 17]
[ 2 18]
[ 2 19]
[3 0]
[3 1]
[3 2]
[3 3]
[3 4]
[3 5]
[3 6]
[3 7]
[3 8]
[3 9]
[ 3 10]
[ 3 11]
[ 3 12]
[ 3 13]
[ 3 14]
[ 3 15]
[ 3 16]
[ 3 17]
[ 3 18]
[ 3 19]
[4 0]
[4 1]
[4 2]
[4 3]
[4 4]
[4 5]
[4 6]
[4 7]
[4 8]
[4 9]
[ 4 10]
[ 4 11]
[ 4 12]
[ 4 13]
[ 4 14]
[ 4 15]
[ 4 16]
[ 4 17]
[ 4 18]
[ 4 19]
[5 0]
[5 1]
[5 2]
[5 3]
[5 4]
[5 5]
[5 6]
[5 7]
[5 8]
[5 9]
[ 5 10]
[ 5 11]
[ 5 12]
[ 5 13]
[ 5 14]
[ 5 15]
[ 5 16]
[ 5 17]
[ 5 18]
[ 5 19]
[6 0]
[6 1]
[6 2]
[6 3]
[6 4]
[6 5]
[6 6]
[6 7]
[6 8]
[6 9]
[ 6 10]
[ 6 11]
[ 6 12]
[ 6 13]
[ 6 14]
[ 6 15]
[ 6 16]
[ 6 17]
[ 6 18]
[ 6 19]
[7 0]
[7 1]
[7 2]
[7

Matrix Exponential

In [2]:
import numpy as np

In [3]:
M = np.random.random((3,3))

M = M + M.conj().T
M

array([[0.99885118, 0.51733729, 1.1659964 ],
       [0.51733729, 0.27723193, 1.66733424],
       [1.1659964 , 1.66733424, 1.66017731]])

In [4]:
eigvals, eigvecs = np.linalg.eig(M)
U = np.transpose(eigvecs, axes=(1,0)) # [orb, num_evecs]

In [5]:
U@U.conj().T

array([[ 1.00000000e+00,  4.47050757e-16, -4.29346910e-17],
       [ 4.47050757e-16,  1.00000000e+00,  4.55399643e-17],
       [-4.29346910e-17,  4.55399643e-17,  1.00000000e+00]])

In [6]:
diagM = (U @ M @ U.conj().T).round(5)
diagM

array([[ 3.42731,  0.     , -0.     ],
       [ 0.     ,  0.37822,  0.     ],
       [-0.     ,  0.     , -0.86927]])

In [7]:
eigvals

array([ 3.42731001,  0.37821756, -0.86926715])

In [8]:
U.conj().T @ diagM @ U

array([[0.99885298, 0.51733613, 1.16599601],
       [0.51733613, 0.2772305 , 1.66733585],
       [1.16599601, 1.66733585, 1.66017652]])

In [9]:
np.diag(diagM)

array([ 3.42731,  0.37822, -0.86927])

In [10]:
exp_diagM = np.diag(np.exp(np.diag(diagM)))
exp_diagM

array([[30.79369619,  0.        ,  0.        ],
       [ 0.        ,  1.45968404,  0.        ],
       [ 0.        ,  0.        ,  0.4192575 ]])

In [11]:
expM = U.conj().T @ exp_diagM @ U
expM

array([[ 7.67594029,  6.27674647, 10.24772604],
       [ 6.27674647,  7.371152  , 10.90452925],
       [10.24772604, 10.90452925, 17.62554543]])

In [12]:
from scipy.linalg import expm

expm(M)

array([[ 7.67593766,  6.27674788, 10.24772696],
       [ 6.27674788,  7.37115229, 10.90452839],
       [10.24772696, 10.90452839, 17.62554572]])