In [1]:
import numpy as np
from pythtb import *
from itertools import product

Notice difference in indicing. The first gets the first element of all the rows, and the second gets the elements of the first row

In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
A[:, 0]


array([1, 3])

In [4]:
A[:][0]


array([1, 2])

In [17]:
nks = 20, 20

In [20]:
k_vals = [range(nk) for nk in nks]
k_idx_arr = np.array(list(product(*k_vals)))

In [21]:
for k in k_idx_arr:
    print (k)

[0 0]
[0 1]
[0 2]
[0 3]
[0 4]
[0 5]
[0 6]
[0 7]
[0 8]
[0 9]
[ 0 10]
[ 0 11]
[ 0 12]
[ 0 13]
[ 0 14]
[ 0 15]
[ 0 16]
[ 0 17]
[ 0 18]
[ 0 19]
[1 0]
[1 1]
[1 2]
[1 3]
[1 4]
[1 5]
[1 6]
[1 7]
[1 8]
[1 9]
[ 1 10]
[ 1 11]
[ 1 12]
[ 1 13]
[ 1 14]
[ 1 15]
[ 1 16]
[ 1 17]
[ 1 18]
[ 1 19]
[2 0]
[2 1]
[2 2]
[2 3]
[2 4]
[2 5]
[2 6]
[2 7]
[2 8]
[2 9]
[ 2 10]
[ 2 11]
[ 2 12]
[ 2 13]
[ 2 14]
[ 2 15]
[ 2 16]
[ 2 17]
[ 2 18]
[ 2 19]
[3 0]
[3 1]
[3 2]
[3 3]
[3 4]
[3 5]
[3 6]
[3 7]
[3 8]
[3 9]
[ 3 10]
[ 3 11]
[ 3 12]
[ 3 13]
[ 3 14]
[ 3 15]
[ 3 16]
[ 3 17]
[ 3 18]
[ 3 19]
[4 0]
[4 1]
[4 2]
[4 3]
[4 4]
[4 5]
[4 6]
[4 7]
[4 8]
[4 9]
[ 4 10]
[ 4 11]
[ 4 12]
[ 4 13]
[ 4 14]
[ 4 15]
[ 4 16]
[ 4 17]
[ 4 18]
[ 4 19]
[5 0]
[5 1]
[5 2]
[5 3]
[5 4]
[5 5]
[5 6]
[5 7]
[5 8]
[5 9]
[ 5 10]
[ 5 11]
[ 5 12]
[ 5 13]
[ 5 14]
[ 5 15]
[ 5 16]
[ 5 17]
[ 5 18]
[ 5 19]
[6 0]
[6 1]
[6 2]
[6 3]
[6 4]
[6 5]
[6 6]
[6 7]
[6 8]
[6 9]
[ 6 10]
[ 6 11]
[ 6 12]
[ 6 13]
[ 6 14]
[ 6 15]
[ 6 16]
[ 6 17]
[ 6 18]
[ 6 19]
[7 0]
[7 1]
[7 2]
[7

Matrix Exponential

In [2]:
import numpy as np

In [162]:
def exp(M):
    shape = M.shape
    nk = len(shape[:-2])
    trans_ax = [i for i in range(nk)] + [nk+1, nk]

    _, eigvecs = np.linalg.eig(M)
    U = np.transpose(eigvecs, axes=trans_ax) # [orb, num_evecs]
    diagM = np.einsum('...ij,...jk->...ik', U, np.einsum('...ij,...jk->...ik', M, np.transpose(U, axes=trans_ax).conj()) )
    # print(diagM[0].round(5))
    exp_diagM = np.exp(np.diagonal(diagM, axis1=-1, axis2=-2))
    expM = np.einsum('...ij, ...jk -> ...ik', np.transpose(U.conj(), axes=trans_ax), np.multiply(U, exp_diagM[..., :, np.newaxis]))
    return(expM)
    

In [163]:
M = np.array([[np.random.random((3,3)) + np.random.random((3,3))*1j for i in range(2)]for j in range(2)])

M = (M + np.transpose(M.conj(), axes=(0, 1, 3, 2)))/2j
M

array([[[[ 0.        -0.55073395j,  0.04471002-0.6866589j ,
          -0.08415431-0.2275885j ],
         [-0.04471002-0.6866589j ,  0.        -0.31077812j,
           0.30090595-0.77359734j],
         [ 0.08415431-0.2275885j , -0.30090595-0.77359734j,
           0.        -0.37366738j]],

        [[ 0.        -0.35026343j, -0.07462434-0.65823757j,
           0.27654116-0.70327052j],
         [ 0.07462434-0.65823757j,  0.        -0.85004599j,
          -0.31469888-0.35760345j],
         [-0.27654116-0.70327052j,  0.31469888-0.35760345j,
           0.        -0.59610559j]]],


       [[[ 0.        -0.10587883j,  0.18664379-0.74327176j,
           0.35094512-0.32163843j],
         [-0.18664379-0.74327176j,  0.        -0.15441899j,
           0.03027048-0.51099461j],
         [-0.35094512-0.32163843j, -0.03027048-0.51099461j,
           0.        -0.39303451j]],

        [[ 0.        -0.81420153j, -0.16861064-0.59422962j,
          -0.181024  -0.34596765j],
         [ 0.16861064-0.59422962

In [167]:
M = np.random.random((3,3)) + np.random.random((3,3))*1j 
M = (M + np.transpose(M.conj(), axes=(1, 0)))/2j
M

array([[ 0.        -0.89561222j,  0.08035646-0.98082962j,
         0.0155703 -0.53204298j],
       [-0.08035646-0.98082962j,  0.        -0.82589424j,
        -0.03762917-0.83639533j],
       [-0.0155703 -0.53204298j,  0.03762917-0.83639533j,
         0.        -0.13174983j]])

In [168]:
exp(M).round(5)

array([[ 0.35135-0.30394j, -0.699  -0.29637j, -0.43844-0.12456j],
       [-0.64004-0.40378j,  0.2457 -0.17261j, -0.38439-0.43519j],
       [-0.43322-0.1543j , -0.41993-0.39631j,  0.66509+0.11295j]])

In [169]:
from scipy.linalg import expm

expm(M).round(5)

array([[ 0.34743-0.29606j, -0.64405-0.40345j, -0.43614-0.15444j],
       [-0.70289-0.29542j,  0.24041-0.16559j, -0.42143-0.39479j],
       [-0.44138-0.12448j, -0.386  -0.43383j,  0.66201+0.11923j]])

In [155]:
%timeit exp2(M)

25.5 μs ± 561 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [156]:
%timeit expm(M)

247 μs ± 9.63 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [157]:
print(np.allclose(expm(M), exp2(M)))

True
